# Generated by Django 5.1 on 2026-03-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='order',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='佣金'),
        ),
        migrations.AddField(
            model_name='order',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='扩展数据'),
        ),
        migrations.AddField(
            model_name='order',
            name='swap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='隔夜利息'),
        ),
        migrations.AddField(
            model_name='order',
            name='ticket',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='订单号'),
        ),
    ]
